#ifndef AUDIO_FORMAT_H_
#define AUDIO_FORMAT_H_

#define MIX_FORMAT AUDIO_S16
#define FFMPEG_FORMAT AV_SAMPLE_FMT_S16
#define FFMPEG_CHANNEL_LAYOUT AV_CH_LAYOUT_STEREO
#define CHANNELS 2
#define SAMPLE_RATE 22050
#define SAMPLES (2 << 13)

#endif