#ifndef AUDIO_FORMAT_H_
#define AUDIO_FORMAT_H_

#define MIX_FORMAT AUDIO_S16
#define FFMPEG_FORMAT AV_SAMPLE_FMT_S16

#define MIX_CHANNEL_LAYOUT 2
#define FFMPEG_CHANNEL_LAYOUT AV_CH_LAYOUT_STEREO

#define MIX_SAMPLE_RATE 44100
#define FFMPEG_SAMPLE_RATE 44100

#endif